### ISSUE TITLE
Error with Path2D not defined

### ISSUE THREAD

**Issue by Gleek** [Timmmm/excalidraw_export#1]
Hey!
Thank you for sharing this package.

It seems that for excalidraw scenes where the draw tool is used the program fails with the following error 

```
λ excalidraw_export  ./Untitled-2022-08-17-1616.excalidraw 
Reading ./Untitled-2022-08-17-1616.excalidraw
Converting to SVG
ReferenceError: Path2D is not defined
    at up (about:blank:3:744260)
    at cp (about:blank:3:741862)
    at about:blank:3:751529
    at Array.forEach (<anonymous>)
    at about:blank:3:751496
    at Lp (about:blank:3:751585)
    at Module.Dp (about:blank:3:753284)
    at renderSvg (about:blank:5:41)
    at excalidrawToSvg (/usr/local/lib/node_modules/excalidraw_export/dist/main.js:55:23)
    at main (/usr/local/lib/node_modules/excalidraw_export/dist/main.js:122:28)
ReferenceError: Path2D is not defined
    at up (about:blank:3:744260)
    at cp (about:blank:3:741862)
    at about:blank:3:751529
    at Array.forEach (<anonymous>)
    at about:blank:3:751496
    at Lp (about:blank:3:751585)
    at Module.Dp (about:blank:3:753284)
    at renderSvg (about:blank:5:41)
    at excalidrawToSvg (/usr/local/lib/node_modules/excalidraw_export/dist/main.js:55:23)
    at main (/usr/local/lib/node_modules/excalidraw_export/dist/main.js:122:28)
ReferenceError: Path2D is not defined
    at up (about:blank:3:744260)
    at cp (about:blank:3:741862)
    at about:blank:3:751529
    at Array.forEach (<anonymous>)
    at about:blank:3:751496
    at Lp (about:blank:3:751585)
    at Module.Dp (about:blank:3:753284)
    at renderSvg (about:blank:5:41)
    at excalidrawToSvg (/usr/local/lib/node_modules/excalidraw_export/dist/main.js:55:23)
    at main (/usr/local/lib/node_modules/excalidraw_export/dist/main.js:122:28)
Writing ./Untitled-2022-08-17-1616.excalidraw.svg
```

This might be related: https://github.com/Automattic/node-canvas/issues/1116

**Comment by Timmmm** [comment]
Damn. Good find. Unfortunately I don't think it's trivial to fix. I looked into Google's `canvas-5-polyfill` which seems to have been abandoned. There is [a fork](https://github.com/hn3000/canvas-5-polyfill) with some patches applied.

However I can't just add it to `package.json` - I need to get it into the jsdom environment somehow which I guess would involve separately bundling it... Ugh, just a bit of a pain.

Sorry. Feel free to have a go though!

**Comment by anonimitoraf** [comment]
Hi @Timmmm, really interested in using this package!

What did you mean by this?
> However I can't just add it to package.json - I need to get it into the jsdom environment somehow which I guess would involve separately bundling it... Ugh, just a bit of a pain.

**Comment by anonimitoraf** [comment]
Hi @Timmmm, really interested in using this package!

What did you mean by this?
> However I can't just add it to package.json - I need to get it into the jsdom environment somehow which I guess would involve separately bundling it... Ugh, just a bit of a pain.

**Comment by Timmmm** [comment]
So I'm not an expert but as I understand it to execute code in JSDOM you basically feed it the JavaScript as text. It's like a browser emulator. You can't just say "call this function but let it use DOM APIs" you have to say "here's the source code for a function. Execute it in a weird sort of virtual JS environment with DOM APIs".

So I think what I'd need to do is make a sub-project containing excalidraw and the canvas polyfill, build & bundle that, then get the output JS file and feed it into JSDOM.

Probably not that bad but a bit of a pain nonetheless. Feel free to have a go if you want!

**Comment by anonimitoraf** [comment]
I see! I've used jsdom (implicitly) via jest + React testing before.

I'm keen to have a go! I'll check it out later

**Comment by anonimitoraf** [comment]
Yeah sorry, I tried. No luck 😢

**Comment by Sachin-12** [comment]
I'm using it with emacs through this [package](https://github.com/wdavew/org-excalidraw/). I get the same error inside emacs. But from command line it works.

**Comment by jkitchin** [comment]
Any solution to this? another package to install? I get this error trying to use it at the command line.

```
Converting to SVG
ReferenceError: Path2D is not defined
    at up (about:blank:3:744260)
    at cp (about:blank:3:741862)
    at about:blank:3:751529
    at Array.forEach (<anonymous>)
    at about:blank:3:751496
    at Lp (about:blank:3:751585)
    at Module.Dp (about:blank:3:753284)
    at renderSvg (about:blank:5:41)
    at excalidrawToSvg (/usr/local/lib/node_modules/excalidraw_export/dist/main.js:55:23)
    at main (/usr/local/lib/node_modules/excalidraw_export/dist/main.js:122:28)
```

**Comment by ziova** [comment]
same, looking for this fix

**Comment by JRJurman** [comment]
@Timmmm - I was able to resolve this by including the polyfill source before the excalidraw source - you can see the changes here: https://github.com/JRJurman/excalidraw-to-svg/commit/5921af3e93f3769b2555c415aae537a0e2a2c02e#diff-e786d06db7b9b61cb9d8c63d7aff5d9d79118485996975a72299d2b79d4630b1R32-R37

Should be easy to include for this project as well 😁

**Comment by Timmmm** [comment]
Ok I did a new release. Please reopen if there are more issues!

**Comment by andrewpeck** [comment]
hi @Timmmm 

sorry to bump this old thread 

I am using `excalidraw_export`  `1.1.0`. 

I tried both node `v18.19.1` and `v22.11.0`. 

This is on Ubuntu 24.01

I also tried cloning the git repo and installing directly from there (instead of via npm repository)

In any case I see the same problem, error message nearly identical to this issue (lines changed).

I'm not very familiar with the javascript ecosystem so I'm pretty lost debugging further. Has this issue resurfaced for anyone else?

Thank so for this tool and for any help you can provide.

```
Reading 1076c327-344a-440d-bf68-ff58c6c16a0b.excalidraw
Converting to SVG
ReferenceError: Path2D is not defined
    at up (about:blank:4:744260)
    at cp (about:blank:4:741862)
    at about:blank:4:751529
    at Array.forEach (<anonymous>)
    at about:blank:4:751496
    at Lp (about:blank:4:751585)
    at Module.Dp (about:blank:4:753284)
    at renderSvg (about:blank:7:41)
    at excalidrawToSvg (/usr/local/lib/node_modules/excalidraw_export/dist/main.js:57:23)
    at main (/usr/local/lib/node_modules/excalidraw_export/dist/main.js:124:28)
```

**Comment by andrewpeck** [comment]
Update:  I checked out an older commit (3cb8b35c92f2c6163b200044fbb074ec9d464ade) of the repo and the tool works ok. 

For me the Path2D error appears in commit bc978b8f559a3b0b53205910799b6662f2ff6479
