### ISSUE TITLE
Error: Not implemented: HTMLCanvasElement.prototype.getContext

### ISSUE THREAD

**Issue by venikx** [Timmmm/excalidraw_export#11]
Apologies for my ignorance, but I was curious as to why this package doesn't include the canvas library as part of its dependencies? 
On my machine, using it as is results in an error:
```sh
Converting to SVG
Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)
    at module.exports (/nix/store/rrbjcd6whgp2mxhwmmslr8s3fsinmn48-excalidraw_export-1.0.4/lib/node_modules/excalidraw_export/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
    at HTMLCanvasElementImpl.getContext (/nix/store/rrbjcd6whgp2mxhwmmslr8s3fsinmn48-excalidraw_export-1.0.4/lib/node_modules/excalidraw_export/node_modules/jsdom/lib/jsdom/living/nodes/HTMLCanvasElement-impl.js:42:5)
    at HTMLCanvasElement.getContext (/nix/store/rrbjcd6whgp2mxhwmmslr8s3fsinmn48-excalidraw_export-1.0.4/lib/node_modules/excalidraw_export/node_modules/jsdom/lib/jsdom/living/generated/HTMLCanvasElement.js:131:58)
    at about:blank:2278:551066
    at 6340 (about:blank:2278:551216)
    at n (about:blank:2278:1376118)
    at about:blank:2278:1377302
    at about:blank:2278:1377311
    at about:blank:2278:207
    at about:blank:2278:211 undefined
```

If I then do  `npm i canvas` inside the repo, and run `node ./dist/main.js test.excalidraw`, it seems to work just fine.
I don't fully understand how people are getting this to run purely in a nodejs environment without having access to the canvas api. Am I not supposed this on the CLI itself?

**Comment by venikx** [comment]
The file I used: https://excalidraw.com/?#json=gIe8-0Z1v0HyOVhNDvGw0,UrVGDDqzc2eHL_8vkZYRag
