### ISSUE TITLE
Update version available on NPM

### ISSUE THREAD

**Issue by skunert** [Timmmm/excalidraw_export#2]
Hi,
super useful package :).

I am not exactly sure about the process, but a new version on npm would be nice.

When installing via `npm install -g excalidraw_export`, I am getting an error about canvas missing:
```
Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)
```

A recent commit seems to address this, but it's not included yet.

**Comment by Timmmm** [comment]
Ah yeah I was trying to fix #1 and failed, but I may as well publish the update - I did that just now. Feel free to reopen this if it doesn't solve your issue!

**Comment by Gleek** [comment]
@Timmmm it seems to fail for me with the same issue, among other errors.
Here's the full output

```
λ excalidraw_export ./c7ec3932-8628-4e85-b517-20849c0fe57b.excalidraw
Reading ./c7ec3932-8628-4e85-b517-20849c0fe57b.excalidraw
Converting to SVG
Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)
    at module.exports (/opt/homebrew/lib/node_modules/excalidraw_export/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
    at HTMLCanvasElementImpl.getContext (/opt/homebrew/lib/node_modules/excalidraw_export/node_modules/jsdom/lib/jsdom/living/nodes/HTMLCanvasElement-impl.js:42:5)
    at HTMLCanvasElement.getContext (/opt/homebrew/lib/node_modules/excalidraw_export/node_modules/jsdom/lib/jsdom/living/generated/HTMLCanvasElement.js:131:58)
    at about:blank:2278:551066
    at 6340 (about:blank:2278:551216)
    at n (about:blank:2278:1376118)
    at about:blank:2278:1377302
    at about:blank:2278:1377311
    at about:blank:2278:207
    at about:blank:2278:211 undefined
Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)
    at module.exports (/opt/homebrew/lib/node_modules/excalidraw_export/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
    at HTMLCanvasElementImpl.getContext (/opt/homebrew/lib/node_modules/excalidraw_export/node_modules/jsdom/lib/jsdom/living/nodes/HTMLCanvasElement-impl.js:42:5)
    at HTMLCanvasElement.getContext (/opt/homebrew/lib/node_modules/excalidraw_export/node_modules/jsdom/lib/jsdom/living/generated/HTMLCanvasElement.js:131:58)
    at 6340 (about:blank:2278:571629)
    at n (about:blank:2278:1376118)
    at about:blank:2278:1377302
    at about:blank:2278:1377311
    at about:blank:2278:207
    at about:blank:2278:211
    at Script.runInContext (node:vm:148:12) undefined
Error: Uncaught [TypeError: Cannot use 'in' operator to search for 'filter' in null]
    at reportException (/opt/homebrew/lib/node_modules/excalidraw_export/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
    at processJavaScript (/opt/homebrew/lib/node_modules/excalidraw_export/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:243:7)
    at HTMLScriptElementImpl._innerEval (/opt/homebrew/lib/node_modules/excalidraw_export/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:176:5)
    at /opt/homebrew/lib/node_modules/excalidraw_export/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:115:12
    at ResourceQueue.push (/opt/homebrew/lib/node_modules/excalidraw_export/node_modules/jsdom/lib/jsdom/browser/resources/resource-queue.js:53:16)
    at HTMLScriptElementImpl._fetchInternalScript (/opt/homebrew/lib/node_modules/excalidraw_export/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:114:21)
    at HTMLScriptElementImpl._eval (/opt/homebrew/lib/node_modules/excalidraw_export/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:170:12)
    at HTMLScriptElementImpl._poppedOffStackOfOpenElements (/opt/homebrew/lib/node_modules/excalidraw_export/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:133:10)
    at JSDOMParse5Adapter.onItemPop (/opt/homebrew/lib/node_modules/excalidraw_export/node_modules/jsdom/lib/jsdom/browser/parser/html.js:175:43)
    at Parser.onItemPop (/opt/homebrew/lib/node_modules/excalidraw_export/node_modules/parse5/dist/cjs/parser/index.js:158:90) TypeError: Cannot use 'in' operator to search for 'filter' in null
    at 6340 (about:blank:2278:571593)
    at n (about:blank:2278:1376118)
    at about:blank:2278:1377302
    at about:blank:2278:1377311
    at about:blank:2278:207
    at about:blank:2278:211
    at Script.runInContext (node:vm:148:12)
    at Object.runInContext (node:vm:300:6)
    at processJavaScript (/opt/homebrew/lib/node_modules/excalidraw_export/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:241:10)
    at HTMLScriptElementImpl._innerEval (/opt/homebrew/lib/node_modules/excalidraw_export/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:176:5)
(node:75400) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
about:blank:2281
          return (await ExcalidrawUtils.exportToSvg({"type":"excalidraw","version":2,"source":"https://excalidraw.com","elements":[{"id":"f95CgvgdtmxsHzokmijsk","type":"freedraw","x":172.3828125,"y":195.75390625,"width":261.734375,"height":210.25390625,"angle":0,"strokeColor":"#1e1e1e","backgroundColor":"transparent","fillStyle":"solid","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":[],"frameId":null,"index":"a0","roundness":null,"seed":1135337995,"version":132,"versionNonce":838953803,"isDeleted":false,"boundElements":null,"updated":1719844036442,"link":null,"locked":false,"points":[[0,0],[0.7109375,0],[3.1484375,0],[12.05859375,0],[19.62109375,0],[28.53125,0],[40.46875,0],[54.0859375,0],[71.38671875,0],[86.79296875,0],[102.19921875,0],[107.38671875,0],[133.37890625,0],[136.625,0],[146.99609375,0],[154.55859375,0],[156.29296875,0],[160.45703125,0],[163.703125,0],[165.4375,0],[167.875,0],[169.609375,0],[169.609375,-1.14453125],[169.609375,-7.46875],[169.609375,-13.79296875],[169.609375,-21.359375],[165.5546875,-29.46484375],[158.63671875,-38.109375],[152.08984375,-43.46875],[146.03515625,-48.0078125],[133.76171875,-54.0625],[129.59375,-54.0625],[126.34375,-54.0625],[123.63671875,-51.8984375],[119.58203125,-43.796875],[118.82421875,-36.234375],[118.82421875,-24.296875],[118.82421875,-12.359375],[120.2265625,9.3671875],[124.1171875,22.984375],[128.0078125,36.6015625],[131.6796875,48.5390625],[134.91796875,57.44921875],[136,60.6953125],[138.265625,68.2578125],[139.66796875,74.578125],[140.96484375,79.765625],[142.046875,83.01171875],[142.5859375,86.2578125],[143.0703125,88.6953125],[143.0703125,91.1328125],[143.0703125,92.8671875],[143.0703125,94.0078125],[143.0703125,95.1484375],[141.60546875,97.09765625],[139.1640625,98.0703125],[135.9140625,98.609375],[130.72265625,98.609375],[124.3984375,98.609375],[116.83203125,98.609375],[109.265625,98.609375],[106.015625,98.06640625],[100.82421875,96.1171875],[96.65625,95.51953125],[94.21484375,94.54296875],[91.7734375,94.0546875],[91.1171875,93.7265625],[90.83984375,93.44921875],[90.83984375,93.171875],[92.57421875,93.171875],[101.484375,92.359375],[113.421875,91.4375],[128.828125,90.41015625],[146.12890625,88.24609375],[167.5546875,85.86328125],[177.92578125,84.1328125],[195.2265625,81.96875],[212.52734375,78.72265625],[226.14453125,76.7734375],[236.515625,75.04296875],[239.76171875,74.5],[247.32421875,73.7421875],[255.65234375,72.546875],[257.38671875,72.109375],[259.12109375,71.671875],[259.7734375,71.671875],[261.1875,71.2890625],[261.4609375,71.2890625],[261.734375,71.2890625],[261.734375,71.01171875],[260.17578125,71.01171875],[256.0078125,70.4140625],[250.81640625,70.4140625],[245.625,70.4140625],[242.375,70.4140625],[238.20703125,70.4140625],[233.015625,70.4140625],[228.84765625,70.4140625],[225.59765625,70.4140625],[222.34765625,70.4140625],[218.1796875,70.4140625],[215.73828125,71.875],[213.5703125,74.578125],[212.59375,77.015625],[211.99609375,81.1796875],[211.99609375,85.34375],[211.99609375,90.53125],[211.99609375,96.8515625],[211.99609375,103.171875],[213.94140625,108.359375],[216.75,114.6796875],[218.85546875,121],[221.44921875,126.1875],[221.98828125,129.43359375],[225.01171875,136.99609375],[225.49609375,139.43359375],[226.08984375,143.59765625],[226.62890625,146.84375],[227.11328125,149.28125],[227.59765625,151.71875],[227.59765625,152.859375],[227.59765625,153.51171875],[227.59765625,154.1640625],[227.59765625,154.4375],[227.59765625,154.7109375],[227.59765625,154.984375],[227.59765625,155.21484375],[226.390625,155.8125],[225.24609375,156.19140625],[225.24609375,156.19140625]],"pressures":[],"simulatePressure":true,"lastCommittedPoint":[225.24609375,156.19140625]}],"appState":{"gridSize":null,"viewBackgroundColor":"#ffffff"},"files":{}})).outerHTML;
          ^

ReferenceError: ExcalidrawUtils is not defined
    at renderSvg (about:blank:2281:11)
    at excalidrawToSvg (/opt/homebrew/lib/node_modules/excalidraw_export/dist/main.js:64:23)
    at main (/opt/homebrew/lib/node_modules/excalidraw_export/dist/main.js:131:28)
    at Object.<anonymous> (/opt/homebrew/lib/node_modules/excalidraw_export/dist/main.js:148:1)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:142:12)
    at node:internal/main/run_main_module:28:49

Node.js v21.7.1



λ excalidraw_export --version
1.0.4
```

**Comment by Gleek** [comment]
https://github.com/Automattic/node-canvas/issues/788 could be related as I can't seem to manually install `canvas` even with the steps there.

**Comment by Gleek** [comment]
Well it did work finally! But I'm not sure exactly how. `canvas` and it's build system was definitely the issue here.
In the end I think moving everything to yarn did it
