### ISSUE TITLE
Error with svg.replaceAll is not a function

### ISSUE THREAD

**Issue by yuzhou721** [Timmmm/excalidraw_export#3]
Report
```
Reading afcc7f1e-b508-4805-b61a-f78d2e7ec6bb.excalidraw
Converting to SVG
Embedding fonts
(node:66669) UnhandledPromiseRejectionWarning: TypeError: svg.replaceAll is not a function
    at embedFonts (/home/yuzhou/.nvm/versions/node/v14.17.5/lib/node_modules/excalidraw_export/dist/main.js:62:15)
    at main (/home/yuzhou/.nvm/versions/node/v14.17.5/lib/node_modules/excalidraw_export/dist/main.js:125:22)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:66669) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:66669) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Is it @Excalidraw/Utils question?

**Comment by Timmmm** [comment]
Hmm I am not sure. Possibly. Could be a JSDOM issue too. I can make the error a bit more meaningful at least.

Can you post the drawing you're using?

**Comment by yuzhou721** [comment]
It is well when not using parameters
``` shell
 ~/org/excalidraw  excalidraw_export afcc7f1e-b508-4805-b61a-f78d2e7ec6bb.excalidraw
Reading afcc7f1e-b508-4805-b61a-f78d2e7ec6bb.excalidraw
Converting to SVG
Writing afcc7f1e-b508-4805-b61a-f78d2e7ec6bb.excalidraw.svg
```

``` shell
 excalidraw_export -rename_fonts afcc7f1e-b508-4805-b61a-f78d2e7ec6bb.excalidraw
Reading true
(node:86988) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received type boolean (true)
    at Object.openSync (fs.js:490:10)
    at Object.readFileSync (fs.js:394:35)
    at main (/home/yuzhou/.nvm/versions/node/v14.17.5/lib/node_modules/excalidraw_export/dist/main.js:120:26)
    at Object.<anonymous> (/home/yuzhou/.nvm/versions/node/v14.17.5/lib/node_modules/excalidraw_export/dist/main.js:139:1)

```

**Comment by Timmmm** [comment]
Ah ok, I will investigate. It used to work so maybe I accidentally broke it somehow. I should probably set up CI too.

**Comment by Timmmm** [comment]
Hmm I can't reproduce this. Is it perhaps because you installed it using one version of Node and are running it using another? Or something like that?

I'm using Node 18.8.0 with fnm (Fast Node Manager).

**Comment by yuzhou721** [comment]
> I'm using Node 18.8.0 with fnm (Fast Node Manager).

I'm using Node 14.17.5.
I'll switch to 18.8.0 and try again.
